src/Wulvern.Web/Wulvern.Intranet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wulvern.Intranet.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Wulvern.Web/Wulvern.Intranet/Controllers/SurfaceControllers/DownloadsSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Wulvern.Infrastructure.Models;

namespace Wulvern.Intranet.Controllers.SurfaceControllers
{
    public class DownloadsSurfaceController : SurfaceController
    {
        [ChildActionOnly]
        [HttpGet]
        [ActionName("GetDownloads")]
        public ActionResult Index()
        {
            List<DownloadModel> model = new List<DownloadModel>()
            {
                new DownloadModel()
                {
                    Title = "Download Title",
                    CategoryName = "HR",
                    UploadedBy = "Mjones",
                    FileType = "PDF",
                    DateUploaded = DateTime.Now,
                    Description = "Lorem Ipsum Dolor sit amet."
                },
                new DownloadModel()
                {
                    Title = "Download Title 2",
                    CategoryName = "HR",
                    UploadedBy = "Graham",
                    FileType = "Word Doc",
                    DateUploaded = DateTime.Now.AddDays(-1),
                    Description = "Indocilis privata locqui"
                },
                 new DownloadModel()
                {
                    Title = "Download Title 3",
                    CategoryName = "HR",
                    UploadedBy = "Mjones",
                    FileType = "PDF",
                    DateUploaded = DateTime.Now.AddDays(-3),
                    Description = "Lorem Ipsum Dolor sit amet."
                },
                new DownloadModel()
                {
                    Title = "Download Title 2",
                    CategoryName = "HR",
                    UploadedBy = "Graham",
                    FileType = "Word Doc",
                    DateUploaded = DateTime.Now.AddDays(-4),
                    Description = "Indocilis privata locqui"
                }
            };

            return PartialView("Downloads", model);
        }

        [HttpPost]
        public ActionResult Search()
        {
            return CurrentUmbracoPage();
        }
    }
}

src/Wulvern.Web/Wulvern.Intranet/Controllers/SurfaceControllers/ServiceDirectorySurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Wulvern.Intranet.Controllers.SurfaceControllers
{
    public class ServiceDirectorySurfaceController : SurfaceController
    {
        public PartialViewResult List( string page = "a" )
        {
          //var productsToShow = this._productsRepository.Products.Where( x => x.ToLower().StartsWith(page) );
          ViewData["currentPage"] = page;
          return PartialView("Companies"); 
        }
    }
}

src/Wulvern.Web/Wulvern.Intranet/Views/Downloads.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

@Html.Action("GetDownloads", "DownloadsSurface")

src/Wulvern.Web/Wulvern.Intranet/Views/Events.cshtml
@using System.Web.UI.WebControls
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

<h2 style="margin-top: 10px;">Events</h2>
@{ var category = new List<System.Web.UI.WebControls.ListItem> { new ListItem { Text = "Intranet", Value = "0" }, new ListItem { Text = "Website", Value = "1" } }; }
<p>Filter by:</p>@Html.DropDownList("category", new SelectList(category , "Value" , "Text"))
@Html.TextBox("Keyword")
<hr />

<div id="datepicker"></div>

<link rel="stylesheet" href="~/css/jquery-ui.css" />
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script type="text/javascript">
    $("#datepicker").datepicker();
</script>

src/Wulvern.Web/Wulvern.Intranet/Views/Head.cshtml
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/main.css"/>
<link rel="icon" type="text/icon" href="~/Images/favicon.ico"
<meta name="google-translate-customization" content="a9ca91c1b228f6ca-9d07614cb39b01da-ged9179c50e273a94-19 /">
<meta name="viewport" content="width=device-width" />
<title>Intranet</title>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/About.cshtml
@{
    Layout = "MasterLayout.cshtml";
}

<div id="annoncementsPanel">
    <h2>Announcements</h2>
</div>

<div id="yourProfile">
   @* @Html.Partial("YourProfile")*@
</div>

<div id="comment">
    @Html.Partial("ShareAComment")
</div>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Contact.cshtml
@model Wulvern.Infrastructure.Models.DownloadModel
@using System.Web.UI.WebControls

@{
    Layout = "MasterLayout.cshtml";
}

<div id="annoncementsPanel">
    <h2>Announcements</h2>
</div>
<div id="downloads">
    <h2>Downloads</h2>
    @{ var category = new List<ListItem> { new ListItem { Text = "Intranet", Value = "0" }, new ListItem { Text = "Website", Value = "1" } }; }
    <p>Filter by:</p>@Html.DropDownList("Category", new SelectList(category , "Value" , "Text"),new {onchange = "getAlldata()"})
    @Html.TextBox("Keyword")
    <hr />
    <div id="download">
        <h2>All downloads...</h2>
        <div style="float: left; width: 200px;">
            <img src="~/Images/wulvern-logo.jpg" />
        </div>
        <div id="text" style="float: left; width: 200px;">
            <h2>mModel.Title</h2>
            <p>mModel.CategoryName mModel.UploadedBy mModel.FileType mModel.DateUploaded</p>
            <p>mModel.Description</p>
        </div>
    </div>
</div>
@Html.Action("GetDownloads", "DownloadsSurface")

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Copy of YourProfile.cshtml
@{
    ViewBag.Title = "YourProfile";
}

<h2>YourProfile</h2>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Head.cshtml
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/main.css"/>
<link rel="icon" type="text/icon" href="~/Images/favicon.ico"
<meta name="google-translate-customization" content="a9ca91c1b228f6ca-9d07614cb39b01da-ged9179c50e273a94-19 /">
<meta name="viewport" content="width=device-width" />
<title>Intranet</title>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/LoginView.cshtml
<ul class="loginView">
    <li><a href="#">Visit Wulvern Website</a></li>
    <li><a href="~/login">Login</a></li>
    <li><a href="~/register">Register</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/MainNavigation.cshtml
<ul class="nav">
    <li><a href="#">Home</a></li>
    <li><a href="#">Explore Wulvern</a></li>
    <li><a href="#">Your profile</a></li>
    <li><a href="#">Service directory</a></li>
    <li><a href="#">Downloads</a></li>
    <li><a href="#">Events</a></li>
    <li><a href="#">Reporting</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/MasterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("Head")     
</head>
    <body>
        <div id="container">
            <div id="header">
                <div id="loginView">
                    @Html.Partial("LoginView")
                </div>
                <div id="logo">
                    <a href="~/home">
                        <img src="~/Images/wulvern-logo.jpg" />
                    </a>
                </div>
                <div id="headerAddress">

                </div>
                <form id="search-form" method="post" runat="server" onclick="searchButton_Click" defaultbutton="searchButton">
                    <div class="search">
                        <input ID="searchTextBox" runat="server" placeholder="Search..." />
                        <input ID="searchButton" type="submit" runat="server" src="~/Images/nav-search-btn.gif" value="Search" />
                    </div>
                </form>
                <nav>
                <div id="mainNav">
                    @Html.Partial("MainNavigation")
                </div>
                </nav>
             </div>
            <div id="leftPane">
                <div id="announcementsPanel">

                </div>
                <div id="content">
                @RenderBody()
            </div> 
            </div>
            <div id="rightPane">
                <div id="events">
                   @* @Html.Partial("Events")*@
                </div>
                <div id="downloads">
                    @*@Html.Partial("Downloads")*@
                </div>
                <div id="banner">
                  @*  @Html.Partial("Banner")*@
                </div>
            </div>        
            <footer>
                Here is the footer
            </footer>
        </div>
    </body>
</html>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Partials/Head.cshtml
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/main.css"/>
<link rel="icon" type="text/icon" href="~/Images/favicon.ico"
<meta name="google-translate-customization" content="a9ca91c1b228f6ca-9d07614cb39b01da-ged9179c50e273a94-19 /">
<meta name="viewport" content="width=device-width" />
<title>Intranet</title>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Partials/LoginView.cshtml
<ul class="loginView">
    <li><a href="#">Visit Wulvern Website</a></li>
    <li><a href="~/login">Login</a></li>
    <li><a href="~/register">Register</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Home/Partials/MainNavigation.cshtml
<ul class="nav">
    <li><a href="#">Home</a></li>
    <li><a href="#">Explore Wulvern</a></li>
    <li><a href="#">Your profile</a></li>
    <li><a href="#">Service directory</a></li>
    <li><a href="#">Downloads</a></li>
    <li><a href="#">Events</a></li>
    <li><a href="#">Reporting</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Homepage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

@Umbraco.Field("bodyText")

src/Wulvern.Web/Wulvern.Intranet/Views/LoginView.cshtml
<ul class="loginView">
    <li><a href="~/login">Login</a></li>
    <li><a href="~/register">Register</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/MainNavigation.cshtml
<ul class="nav">
    <li><a href="#">Home</a></li>
    <li><a href="#">Explore Wulvern</a></li>
    <li><a href="#">Your profile</a></li>
    <li><a href="#">Service directory</a></li>
    <li><a href="#">Downloads</a></li>
    <li><a href="#">Events</a></li>
    <li><a href="#">Reporting</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/MasterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("Head")     
</head>
    <body>
        <div id="container">
            <div id="header">
                <div id="loginView">
                    @Html.Partial("LoginView")
                </div>
                <div id="logo">
                    <a href="~/home">
                        <img src="~/Images/wulvern-logo.jpg" />
                    </a>
                </div>
                <div id="headerAddress">

                </div>
                <form id="search-form" method="post" runat="server" onclick="searchButton_Click" defaultbutton="searchButton">
                    <div class="search">
                        <input ID="searchTextBox" runat="server" placeholder="Search..." />
                        <input ID="searchButton" type="submit" runat="server" src="~/Images/nav-search-btn.gif" value="Search" />
                    </div>
                </form>
                <nav>
                <div id="mainNav">
                    @Html.Partial("MainNavigation")
                </div>
                </nav>
             </div>
            <div id="leftPane">
                <div id="announcementsPanel">
                    <h3>Announcements</h3>
                </div>
                <div id="content">
                @RenderBody()
            </div> 
            </div>
            <div id="rightPane">
                <div id="profile">
                    @Html.Partial("Profile")
                </div>
                <div id="events">
                   @Html.Partial("Events")
                </div>
                <div id="popularDownloads">
                   @Html.Partial("PopularDownloads")
                </div>
                <div id="banner">
                  @Html.Partial("Banner")
                </div>
            </div>        
            <footer>
                <div class="footer">
                    Here is the footer
                </div>
            </footer>
        </div>
    </body>
</html>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $("category").change(function () {
        alert("changed");
    })
</script>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Banner.cshtml
<h2 style="margin-top: 10px;">Banner</h2>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Companies.cshtml
<h2>Company Name</h2>
<p>Category:</p>
<p>Telephone number:</p>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Downloads.cshtml
@using Wulvern.Infrastructure.Models
@model List<DownloadModel>
@using System.Web.UI.WebControls
<div id="downloads">
    <h2>Downloads</h2>
    @{ var category = new List<ListItem> { new ListItem { Text = "Intranet", Value = "0" }, new ListItem { Text = "Website", Value = "1" } }; }
    <p>Filter by:</p>@Html.DropDownList("category", new SelectList(category , "Value" , "Text"))
    @Html.TextBox("Keyword")
    <hr />
        @foreach(var item in Model)
        {
            <div id="download">
                <h2>All downloads...</h2>
                <div style="float: left; width: 200px;">
                    <img src="~/Images/wulvern-logo.jpg" />
                </div>
                <div style=""float: left;">
                    <h2>@item.Title</h2>
                    <p>@item.CategoryName @item.UploadedBy @item.FileType @item.DateUploaded</p>
                    <p>@item.Description</p>
                </div>
            </div>
        }
</div>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Events.cshtml
<h2 style="margin-top: 10px">Upcoming Events</h2>
<ul>
    <li>Event 1</li>
    <li>Event 2</li>
    <li>Event 3</li>
    <li>Event 4</li>
    <li>Event 5</li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Head.cshtml
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/main.css"/>
<link rel="icon" type="text/icon" href="~/Images/favicon.ico"
<meta name="google-translate-customization" content="a9ca91c1b228f6ca-9d07614cb39b01da-ged9179c50e273a94-19 /">
<meta name="viewport" content="width=device-width" />
<title>Intranet</title>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/LoginView.cshtml
<ul class="loginView">
    <li><a href="#">Visit Wulvern Website</a></li>
    <li><a href="~/login">Login</a></li>
    <li><a href="~/register">Register</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/MainNavigation.cshtml
<ul class="nav">
    <li><a href="~/">Home</a></li>
    <li><a href="#">Explore Wulvern</a></li>
    <li><a href="~/your-profile">Your profile</a></li>
    <li><a href="~/service-directory">Service directory</a></li>
    <li><a href="~/downloads">Downloads</a></li>
    <li><a href="~/events">Events</a></li>
    <li><a href="#">Reporting</a></li>
</ul>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/PopularDownloads.cshtml
@using Wulvern.Infrastructure.Models
@using System.Web.UI.WebControls
<div id="downloads">
    <h2 style="margin-top:10px">Popular downloads</h2>
        <div id="download">
            <div style=""float: left;">
                Event name<br />
                Event Description
            </div>
        </div>
</div>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/Profile.cshtml
<h2 style="margin-top: 5px">Your profile</h2>
<div id="image">
    <img src="~/Images/wulvern-logo.jpg" />
</div>
<div id="text">
    Mark Jones<br />
    IT<br />
</div>
<div style="clear: both;"></div>

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/ShareAComment.cshtml
@using System.Web.UI.WebControls
    <h3>Share a comment with your colleagues</h3>
    @{ var sender = new List<ListItem> { new ListItem { Text = "You", Value = "0" }, new ListItem { Text = "Me", Value = "1" } }; }
    @Html.DropDownList("Sender", new SelectList(sender , "Value" , "Text"),new {onchange = "getAlldata()"})
    @Html.TextBox("Title")
    @Html.TextBox("Update")
    @{ var category = new List<ListItem> { new ListItem { Text = "About You", Value = "0" }, new ListItem { Text = "About Me", Value = "1" } }; }
    @Html.DropDownList("Category", new SelectList(category , "Value" , "Text"),new {onchange = "getAlldata()"})

src/Wulvern.Web/Wulvern.Intranet/Views/Partials/YourProfile.cshtml
<h2>Your Profile</h2>
<img src="~/Images/wulvern-logo.jpg">
<div id="profileText">
    <p><strong>Name:</strong></p>
    <p><strong>Job title:</strong></p>
    <p><strong>Dept:</strong></p>
    <p><strong>Location:</strong></p>
    <p><strong>Extension:</strong></p>
    <p><strong>Mobile:</strong></p>
    <p><strong>Email:</strong></p>
</div>

src/Wulvern.Web/Wulvern.Intranet/Views/ServiceDirectory.cshtml
@using Wulvern.Intranet.Helpers
@using System.Web.UI.WebControls
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

<h2>Service Directory</h2>
@{ var category = new List<ListItem> { new ListItem { Text = "Intranet", Value = "0" }, new ListItem { Text = "Website", Value = "1" } }; }
<p>Filter by:</p>@Html.DropDownList("category", new SelectList(category , "Value" , "Text"))
@Html.TextBox("Keyword")
<hr />
<div class="dp-highlighter">
    <div class="bar">
        <div class="tools"></div>
    </div>
	@Html.AlphabeticalPager("A", x => Url.Action("List", "ServiceDirectorySurface", new {page = x}))
</div>

src/Wulvern.Web/Wulvern.Intranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

src/Wulvern.Web/Wulvern.Intranet/Views/YourProfile.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

@Html.Partial("YourProfile")

@Html.Partial("ShareAComment")