src/Wulvern.Web/Wulvern.Web/Controllers/SurfaceControllers/JobApplicationSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Wulvern.Web.Helpers;
using Wulvern.Web.Models;


namespace Wulvern.Web.Controllers.SurfaceControllers
{ 
    public class JobApplicationSurfaceController : SurfaceController
    {
		//Method for rendering partial view with @Html.Action("RenderJobApplication","JobApplicationSurface");
		[ChildActionOnly]
        public ActionResult RenderJobApplication(){
            return PartialView("JobApplication", new JobApplicationModel());
		}

		//endpoint for posting data to a surface controller action
	    [HttpPost]
        public ActionResult HandleJobApplication(JobApplicationModel model)
        {
            var CVUpload = Request.Files["CVUpload"];
            var CoveringLetterUpload = Request.Files["CoveringLetterUpload"];
            
            if (!(CVUpload.ContentType == "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
                CVUpload.ContentType == "application/pdf"))
            {
                ModelState.AddModelError("CVUpload", "Only .docx and .pdf file allowed");
            }

            if (!(CoveringLetterUpload.ContentType == "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
                CoveringLetterUpload.ContentType == "application/pdf"))
            {
                ModelState.AddModelError("CoveringLetterUpload", "Only .docx and .pdf file allowed");
            }

			//model not valid, do not save, but return current umbraco page
			if (!ModelState.IsValid)
			{
				//Perhaps you might want to add a custom message to the TempData or ViewBag
				//which will be available on the View when it renders (since we're not 
				//redirecting)          
				return CurrentUmbracoPage();
			}
            
			//if validation passes perform whatever logic
			//In this sample we keep it empty, but try setting a breakpoint to see what is posted here

            if (CurrentPage.DocumentTypeAlias == "Vacancy")
            {
                model.JobTitle = CurrentPage.GetProperty("title").Value.ToString();
                model.JobId = CurrentPage.GetProperty("jobId").Value.ToString();
            }
            else
            {
                model.JobTitle = "Generic";
                model.JobId = "-";
            }
            // string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
            // Removed this line as dont think we need to save Doc to another location
            //file.SaveAs(Path.Combine(Server.MapPath("~/UploadedCV"), fileName));

            //model.CV = cvFile.InputStream;
            //model.CVName = cvFile.FileName;

            //model.CoverLetter = clFile.InputStream;
            //model.CoverLetterName = clFile.FileName;

            ModelState.Clear();
            // Have removed Send Email from controller responsibility and added as helper method
            var mailHelper = new SendEmailHelper();
            if (mailHelper.SendEmail(model, CVUpload, CoveringLetterUpload))
            {
                TempData.Add("CustomMessage", "Your application was successfully submitted at " + DateTime.Now);
                return RedirectToUmbracoPage(1953);
            }
            else
            {
                TempData.Add("CustomMessage", "There was a problem submitting your application");
            }
            
			//Perhaps you might want to store some data in TempData which will be available 
			//in the View after the redirect below. An example might be to show a custom 'submit
			//successful' message on the View, for example:
            

			//redirect to current page to clear the form
			return RedirectToCurrentUmbracoPage();

			//Or redirect to specific page
            //return RedirectToUmbracoPage(1953);
        }
	}
}

src/Wulvern.Web/Wulvern.Web/Views/BlankTemplate.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ReachmailApi
@using Wulvern.Web.ExtensionMethods;
@using Wulvern.Web.Helpers;
@using Wulvern.Core.Domain
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    @Html.Partial("Head")
</head>
<body>
<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="socialSideBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" class="facebookLink" title="Facebook" target="_blank"></a><a href="https://www.youtube.com/user/Wulvern" class="youtubeLink" title="Youtube" target="_blank"></a><a href="https://twitter.com/intent/user?screen_name=Wulvern" class="twitterLink" title="Twitter" target="_blank"></a><a href="https://plus.google.com/111898600279461860850/posts" class="googleLink" title="Google Plus" target="_blank"></a></div>

	<!-- HEADER -->
<div class="headWrapper">
  @Html.Partial("HeadWrapper")
  <!-- NAVIGATION -->
  <nav class="wBlueBg shadow clearfix">
    @Html.CachedPartial("DesktopNavigation", Model.Content, 10000, true, false, null)
  </nav>
  
  <!-- END NAVIGATION --> 
</div>

<!-- BEADCRUMB TRAIL -->
<div class="wraper">
    <div class="breadcrumb">
        @Html.Partial("Breadcrumbs")
    </div>
</div>
<!-- END BEADCRUMB TRAIL --> 

<div class="wraper clearfix">

<!-- SIDE NAVIGATION -->

  <div  class="sideNav">
    
    <!-- SIDE NAV BUTTONS -->
	@Html.Partial("SideNavButtons")
	<!-- END SIDE NAV BUTTONS -->
    
  </div>
  
<!-- END SIDE NAVIGATION --> 



<!-- CONTENT AREA -->
<div class="contentArea">
  <h1>@Umbraco.Field("pageTitle")</h1>
   @Html.Raw(@Model.Content.GetPropertyValue("bodyText"))
   <!-- You tube videos -->
  <section id="youTube">
        @if (Model.Content.HasProperty("showYouTubeVideo") &&
            Model.Content.GetPropertyValue<bool>("showYouTubeVideo") == true)
        {
          <!-- You tube video -->
          <object width="425" height="350">
      <param name="movie" value="http://www.youtube.com/v/AyPzM5WK8ys" />
      <param name="wmode" value="transparent" />
      <embed src="@Umbraco.Field("youTubeVideoLink")"
             type="application/x-shockwave-flash"
             wmode="transparent" width="670" height="400" />
    </object>
        }
    </section>
  
    @Html.Partial("DownloadLinks")
</div>



<!-- END CONTENT AREA -->
</div>
<div class="wraper">
  <div class="socialFooterBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" target="_blank"><img src="/images/social/facebook_bottom.png" width="51" height="43" alt="Facebook"/></a> <a href="https://www.youtube.com/user/Wulvern" target="_blank"><img src="/images/social/youtube_bottom.png" width="50" height="43" alt="Youtube"/></a> <a href="https://twitter.com/intent/user?screen_name=Wulvern" target="_blank"><img src="/images/social/twitter_bottom.png" width="50" height="43" alt="Twitter"/></a> <a href="https://plus.google.com/111898600279461860850/posts" target="_blank"><img src="/images/social/googleplus_bottom.png" width="51" height="43" alt="GooglePlus"/></a> </div>
</div>
<!-- FOOTER -->
@Html.Partial("Footer")
<!-- END FOOTER --> 
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> 
<script>window.jQuery || document.write('<script src="~/js/vendor/jquery-1.11.0.min.js"><\/script>')</script> 
<script src="~/js/vendor/jquery.dlmenu.js"></script> 
<script>
	$(function() {
		$( '#dl-menu').dlmenu();
	});

	$('#searchForm').submit(function () {
	    alert("searching");
	    var searchString = $("#search").val();
	    $("#searchForm").attr("action", "/search-results" + "?search=" + searchString);
	    if (searchString != "")
	        $("#searchForm").attr("action", "/search-results" + "?search=" + searchString);
	});
</script> 
<script src="~/js/vendor/jquery.infieldlabel.min.js"></script> 
<script src="~/js/vendor/jquery.cycle2.min.js"></script> 
<script src="~/js/vendor/jquery.cycle2.swipe.min.js"></script> 
<script src="~/js/main.js"></script>
</body>
</html>

src/Wulvern.Web/Wulvern.Web/Views/Downloads.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ReachmailApi
@using Wulvern.Web.ExtensionMethods;
@using Wulvern.Web.Helpers;
@using Wulvern.Core.Domain
@Html.Partial("Counter")
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
@Html.Partial("Head")
</head>
<body>
<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="socialSideBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" class="facebookLink" title="Facebook" target="_blank"></a><a href="https://www.youtube.com/user/Wulvern" class="youtubeLink" title="Youtube" target="_blank"></a><a href="https://twitter.com/intent/user?screen_name=Wulvern" class="twitterLink" title="Twitter" target="_blank"></a><a href="https://plus.google.com/111898600279461860850/posts" class="googleLink" title="Google Plus" target="_blank"></a></div>

<!-- HEADER -->
<div class="headWrapper">
 @Html.Partial("HeadWrapper")
  <!-- NAVIGATION -->
  <nav class="wBlueBg shadow clearfix">
    @Html.Partial("DesktopNavigation")
  </nav>
  
  <!-- END NAVIGATION --> 
</div>

<!-- BEADCRUMB TRAIL -->
<div class="wraper">
  <div class="breadcrumb"><a href="#">Home</a> / downloads </div>
</div>
<!-- END BEADCRUMB TRAIL -->

<div class="wraper clearfix"> 
  
  <!-- SIDE NAVIGATION -->
  
  <div  class="sideNav">
    @Html.Partial("DownloadCategories", Model.Content)
    
    <!-- SIDE NAV BUTTONS --> 
	@Html.Partial("SideNavButtons")
    <!-- END SIDE NAV BUTTONS --> 
  </div>
  
  <!-- END SIDE NAVIGATION --> 
  
  <!-- CONTENT AREA -->
  <div class="contentArea">
    <h1>@Umbraco.Field("pageTitle")</h1>
    <!-- DOWNLOADS CAT DROP DOWN -->
    @Html.Partial("DownloadCategoriesDropdown", Model.Content)

    <!-- END  DOWNLOADS CAT DROP DOWN --> 
    
    <!-- DOWNLOADS -->
    @Html.Partial("DownloadByCategory", Model.Content)
</div>
    
  <!-- END DOWNLOADS --> 
  
  <!-- COMMON BUTTONS -->
  
@Html.Partial("BottomQuicklinks", Model.Content)
  
  <!-- END COMMON BUTTONS --> 
  
  <!-- END CONTENT AREA --> 
</div>
<div class="wraper">
  <div class="socialFooterBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" target="_blank"><img src="/images/social/facebook_bottom.png" width="51" height="43" alt="Facebook"/></a> <a href="https://www.youtube.com/user/Wulvern" target="_blank"><img src="/images/social/youtube_bottom.png" width="50" height="43" alt="Youtube"/></a> <a href="https://twitter.com/intent/user?screen_name=Wulvern" target="_blank"><img src="/images/social/twitter_bottom.png" width="50" height="43" alt="Twitter"/></a> <a href="https://plus.google.com/111898600279461860850/posts" target="_blank"><img src="/images/social/googleplus_bottom.png" width="51" height="43" alt="GooglePlus"/></a> </div>
</div>
<!-- FOOTER -->
@Html.Partial("Footer")
<!-- END FOOTER --> 
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> 
<script>window.jQuery || document.write('<script src="~/js/vendor/jquery-1.11.0.min.js"><\/script>')</script> 
<script src="~/js/vendor/jquery.dlmenu.js"></script> 
<script>
	$(function() {
		$( '#dl-menu' ).dlmenu();
	});

	
</script> 
<script src="~/js/vendor/jquery.infieldlabel.min.js"></script> 
<script src="~/js/vendor/jquery.cycle2.min.js"></script> 
<script src="~/js/vendor/jquery.cycle2.swipe.min.js"></script> 
<script src="~/js/main.js"></script>
</body>
</html>

src/Wulvern.Web/Wulvern.Web/Views/Event.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ReachmailApi
@using Wulvern.Web.ExtensionMethods;
@using Wulvern.Web.Helpers;
@using Wulvern.Core.Domain
@Html.Partial("Counter")
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    @Html.Partial("Head")
</head>
<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <div class="socialSideBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" class="facebookLink" title="Facebook" target="_blank"></a><a href="https://www.youtube.com/user/Wulvern" class="youtubeLink" title="Youtube" target="_blank"></a><a href="https://twitter.com/intent/user?screen_name=Wulvern" class="twitterLink" title="Twitter" target="_blank"></a><a href="https://plus.google.com/111898600279461860850/posts" class="googleLink" title="Google Plus" target="_blank"></a></div>


    <!-- HEADER -->
    <div class="headWrapper">
        @Html.Partial("HeadWrapper")
        <!-- NAVIGATION -->
        <nav class="wBlueBg shadow clearfix">
            @Html.Partial("DesktopNavigation")
        </nav>

        <!-- END NAVIGATION -->
    </div>

    <!-- BEADCRUMB TRAIL -->
    <div class="wraper">
        <div class="breadcrumb">
            @Html.Partial("Breadcrumbs")
        </div>
    </div>
    <!-- END BEADCRUMB TRAIL -->

    <div class="wraper clearfix">

        <!-- SIDE NAVIGATION -->

        <div class="sideNav">

            <!-- SIDE NAV BUTTONS -->
            @Html.Partial("SideNavButtons")
            <!-- END SIDE NAV BUTTONS -->

        </div>

        <!-- END SIDE NAVIGATION -->

        <!-- CONTENT AREA -->
        <div class="contentArea">

            <h1>@Model.Content.GetPropertyValue("title")</h1>
            <div class="clearfix">
                <div class="eventDate">
                    <p class="eventDateLocation">Date &amp; time</p>
                    <p>
                        @{
                            DateTime eventDate = (DateTime)Model.Content.GetPropertyValue("eventDate");
                        }
                        @DateHelper.getDateEventLong(eventDate)
                    </p>
                </div>
                <div class="eventLocation">
                    <p class="eventDateLocation">Location</p>
                    <p>
                        @Model.Content.GetPropertyValue("location")
                    </p>
                </div>
            </div>
            <div class="clearfix">
                <p>
                    @if (Model.Content.HasValue("image"))
                    {
                        var image = Model.Content.GetPropertyValue("image");
                        <img src="@Umbraco.TypedMedia(image).Url" class="img-responsive" />
                    }

                </p>
                @Model.Content.GetPropertyValue("description")
            </div>
            <div class="share clearfix">
                <span class="desktop">Share</span>
                <a href="http://www.facebook.com/share.php?title=@Html.Encode(@Model.Content.GetPropertyValue("title"))" class="facebookFooterLink" title="Facebook" target="_blank"></a>

                <a href="https://twitter.com/share" class="twitterFooterLink twitterpopup" title="Twitter" target="_blank"></a>

                <a href="https://plus.google.com/share?url={URL}" onclick="javascript:window.open(this.href,
  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                    class="googleFooterLink" title="Google Plus" target="_blank"></a>

                @if (Model.Content.HasValue("image"))
                {
                    var image = Model.Content.GetPropertyValue("image");
                    string host = "http://" + HttpContext.Current.Request.Url.Host;

                    string imageWithPath = Umbraco.TypedMedia(image).Url;
                    <a href="http://pinterest.com/pin/create/button/?media=@Html.Encode(host + imageWithPath)&description=@Html.Encode(@Model.Content.GetPropertyValue("title"))" class="pintrestFooterLink" title="Pintrest" target="_blank"></a>
                }


            </div>
        </div>

        <!-- END CONTENT AREA -->
    </div>

    <!-- COMMON BUTTONS -->

    @Html.Partial("BottomQuicklinks", Model.Content)

    <!-- END COMMON BUTTONS -->

    <div class="wraper">
  <div class="socialFooterBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" target="_blank"><img src="/images/social/facebook_bottom.png" width="51" height="43" alt="Facebook"/></a> <a href="https://www.youtube.com/user/Wulvern" target="_blank"><img src="/images/social/youtube_bottom.png" width="50" height="43" alt="Youtube"/></a> <a href="https://twitter.com/intent/user?screen_name=Wulvern" target="_blank"><img src="/images/social/twitter_bottom.png" width="50" height="43" alt="Twitter"/></a> <a href="https://plus.google.com/111898600279461860850/posts" target="_blank"><img src="/images/social/googleplus_bottom.png" width="51" height="43" alt="GooglePlus"/></a> </div>
</div>
    <!-- FOOTER -->
    @Html.Partial("Footer")
    <!-- END FOOTER -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="~/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>
    <script src="~/js/vendor/jquery-ui.min.js"></script>

    <script src="~/js/vendor/jquery.dlmenu.js"></script>
    <script>
        $(function () {
            $('#dl-menu').dlmenu();
        });
    </script>
    <script src="~/js/vendor/jquery.infieldlabel.min.js"></script>
    <script src="~/js/vendor/jquery.cycle2.min.js"></script>
    <script src="~/js/vendor/jquery.cycle2.swipe.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

src/Wulvern.Web/Wulvern.Web/Views/JobAdvert.cshtml
@using umbraco.MacroEngines
@using umbraco.presentation.nodeFactory
@using Wulvern.Web.ExtensionMethods
@using Wulvern.Infrastructure.Models
@using Wulvern.Web.Helpers
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@Html.Partial("Counter")
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    @Html.Partial("Head")
</head>
<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <div class="socialSideBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" class="facebookLink" title="Facebook" target="_blank"></a><a href="https://www.youtube.com/user/Wulvern" class="youtubeLink" title="Youtube" target="_blank"></a><a href="https://twitter.com/intent/user?screen_name=Wulvern" class="twitterLink" title="Twitter" target="_blank"></a><a href="https://plus.google.com/111898600279461860850/posts" class="googleLink" title="Google Plus" target="_blank"></a></div>

    <!-- HEADER -->
    <div class="headWrapper">
        @Html.Partial("HeadWrapper")
        <!-- NAVIGATION -->
        <nav class="wBlueBg shadow clearfix">
            @Html.Partial("DesktopNavigation")
        </nav>

        <!-- END NAVIGATION -->
    </div>

    <!-- BEADCRUMB TRAIL -->
    <div class="wraper">
        <div class="breadcrumb">
            @Html.Partial("Breadcrumbs")
        </div>
    </div>
    <!-- END BEADCRUMB TRAIL -->

    <div class="wraper clearfix">

        <!-- SIDE NAVIGATION -->

        <div class="sideNav">
            @Html.Partial("SideNavigation")

            <!-- SIDE NAV BUTTONS -->
            @Html.Partial("SideNavButtons")
            <!-- END SIDE NAV BUTTONS -->

        </div>

        <!-- END SIDE NAVIGATION -->

        <!-- CONTENT AREA -->
        <div class="contentArea">
            @{
                var publishedContent = CurrentPage;
            }
            <!-- VACANCY -->
            @{
                DateTime closingDate = @CurrentPage.ClosingDate;
                var jobAdvert = @publishedContent.GetPropertyValue("jobAdvert");
                var jobDescription = @publishedContent.GetPropertyValue("jobDescription");
                var jobId = @publishedContent.GetPropertyValue("jobId");
            
                <div class="vacancy clearfix">
                    <div class="closingDate">Closing date<br />@DateHelper.getDateEventShort(closingDate)</div>
                    <h2>@publishedContent.GetPropertyValue("title")</h2>
                    <h3>@publishedContent.GetPropertyValue("location")</h3>
                    <h4>@publishedContent.GetPropertyValue("salary")</h4>

                    @Html.Raw(publishedContent.GetPropertyValue("description"))

                    @if (publishedContent.HasProperty("extendedDescription") && publishedContent.GetPropertyValue("extendedDescription").ToString() != "")
                    {

                        <a href="#" onclick="toggleReadMore('readmore_@jobId')" class="link_readmore_@jobId">Read more &#8250;</a>
                        <div class="hide" id="readmore_@jobId">
                            @Html.Raw(publishedContent.GetPropertyValue("extendedDescription"))
                            <p><a href="#" onclick="toggleReadMore('readmore_@jobId')" class="readLessToggle">Read less &#8249;</a></p>
                        </div>
                    
                    }

                    <br />
                    <br />

                    <a target="_blank" href="@Umbraco.TypedMedia(jobAdvert).Url">Download job advert (PDF) &#8250;</a><br />
                    <a target="_blank" href="@Umbraco.TypedMedia(jobDescription).Url">Download job description (PDF) &#8250;</a>
                    <h2>Apply now</h2>
                    <div class="mobile tablet">
                        <h3>How to apply</h3>
                        <p>Send your CV with a covering letter telling us why you think you are suitable for the position to <a href="mailto:jobs@wulvern.org.uk">jobs@wulvern.org.uk</a></p>
                    </div>
                    <div class="jobAppForm" style="display:block">
                        <div class="formContainer clearfix">
                    @Html.Action("RenderJobApplication","JobApplicationSurface")
                </div>
                    </div>
                    
                </div>
            }

        </div>

        <!-- COMMON BUTTONS -->

        @Html.Partial("BottomQuicklinks", Model.Content)

        <!-- END COMMON BUTTONS -->

        <!-- END CONTENT AREA -->
    </div>
    <div class="wraper">
  <div class="socialFooterBar"><a href="https://www.facebook.com/WulvernHousing?ref=stream" target="_blank"><img src="/images/social/facebook_bottom.png" width="51" height="43" alt="Facebook"/></a> <a href="https://www.youtube.com/user/Wulvern" target="_blank"><img src="/images/social/youtube_bottom.png" width="50" height="43" alt="Youtube"/></a> <a href="https://twitter.com/intent/user?screen_name=Wulvern" target="_blank"><img src="/images/social/twitter_bottom.png" width="50" height="43" alt="Twitter"/></a> <a href="https://plus.google.com/111898600279461860850/posts" target="_blank"><img src="/images/social/googleplus_bottom.png" width="51" height="43" alt="GooglePlus"/></a> </div>
</div>
    <!-- FOOTER -->
    @Html.Partial("Footer")
    <!-- END FOOTER -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="~/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>
    <script src="~/js/vendor/jquery.dlmenu.js"></script>
    <script>
        $(function () {
            $('#dl-menu').dlmenu();
        });
    </script>
    <script src="~/js/vendor/jquery.infieldlabel.min.js"></script>
    <script src="~/js/vendor/jquery.cycle2.min.js"></script>
    <script src="~/js/vendor/jquery.cycle2.swipe.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

src/Wulvern.Web/Wulvern.Web/Views/JobListings.cshtml
@using Wulvern.Infrastructure.Models
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
}

@Html.Partial("CVUpload", new CVUploadModel())